# fly.toml app configuration file generated for mhealth-lively-brook-7047 on 2024-03-04T14:53:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mhealth'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 7000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
