# fly.toml app configuration file generated for mhealth on 2023-08-30T17:21:00+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mhealth"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 7000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
